apiVersion: v1
kind: Service
metadata:
  name: ack-dynamodb-metrics-service
  namespace: ack-system
spec:
  selector:
    app.kubernetes.io/name: ack-dynamodb-controller
  ports:
    - name: metricsport
      port: 8080
      targetPort: http
      protocol: TCP
  type: NodePort
