// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ApproximateCreationDateTimePrecision string

const (
	ApproximateCreationDateTimePrecision_MICROSECOND ApproximateCreationDateTimePrecision = "MICROSECOND"
	ApproximateCreationDateTimePrecision_MILLISECOND ApproximateCreationDateTimePrecision = "MILLISECOND"
)

type AttributeAction string

const (
	AttributeAction_ADD    AttributeAction = "ADD"
	AttributeAction_DELETE AttributeAction = "DELETE"
	AttributeAction_PUT    AttributeAction = "PUT"
)

type BackupStatus_SDK string

const (
	BackupStatus_SDK_AVAILABLE BackupStatus_SDK = "AVAILABLE"
	BackupStatus_SDK_CREATING  BackupStatus_SDK = "CREATING"
	BackupStatus_SDK_DELETED   BackupStatus_SDK = "DELETED"
)

type BackupType string

const (
	BackupType_AWS_BACKUP BackupType = "AWS_BACKUP"
	BackupType_SYSTEM     BackupType = "SYSTEM"
	BackupType_USER       BackupType = "USER"
)

type BackupTypeFilter string

const (
	BackupTypeFilter_ALL        BackupTypeFilter = "ALL"
	BackupTypeFilter_AWS_BACKUP BackupTypeFilter = "AWS_BACKUP"
	BackupTypeFilter_SYSTEM     BackupTypeFilter = "SYSTEM"
	BackupTypeFilter_USER       BackupTypeFilter = "USER"
)

type BatchStatementErrorCodeEnum string

const (
	BatchStatementErrorCodeEnum_AccessDenied                    BatchStatementErrorCodeEnum = "AccessDenied"
	BatchStatementErrorCodeEnum_ConditionalCheckFailed          BatchStatementErrorCodeEnum = "ConditionalCheckFailed"
	BatchStatementErrorCodeEnum_DuplicateItem                   BatchStatementErrorCodeEnum = "DuplicateItem"
	BatchStatementErrorCodeEnum_InternalServerError             BatchStatementErrorCodeEnum = "InternalServerError"
	BatchStatementErrorCodeEnum_ItemCollectionSizeLimitExceeded BatchStatementErrorCodeEnum = "ItemCollectionSizeLimitExceeded"
	BatchStatementErrorCodeEnum_ProvisionedThroughputExceeded   BatchStatementErrorCodeEnum = "ProvisionedThroughputExceeded"
	BatchStatementErrorCodeEnum_RequestLimitExceeded            BatchStatementErrorCodeEnum = "RequestLimitExceeded"
	BatchStatementErrorCodeEnum_ResourceNotFound                BatchStatementErrorCodeEnum = "ResourceNotFound"
	BatchStatementErrorCodeEnum_ThrottlingError                 BatchStatementErrorCodeEnum = "ThrottlingError"
	BatchStatementErrorCodeEnum_TransactionConflict             BatchStatementErrorCodeEnum = "TransactionConflict"
	BatchStatementErrorCodeEnum_ValidationError                 BatchStatementErrorCodeEnum = "ValidationError"
)

type BillingMode string

const (
	BillingMode_PAY_PER_REQUEST BillingMode = "PAY_PER_REQUEST"
	BillingMode_PROVISIONED     BillingMode = "PROVISIONED"
)

type ComparisonOperator string

const (
	ComparisonOperator_BEGINS_WITH  ComparisonOperator = "BEGINS_WITH"
	ComparisonOperator_BETWEEN      ComparisonOperator = "BETWEEN"
	ComparisonOperator_CONTAINS     ComparisonOperator = "CONTAINS"
	ComparisonOperator_EQ           ComparisonOperator = "EQ"
	ComparisonOperator_GE           ComparisonOperator = "GE"
	ComparisonOperator_GT           ComparisonOperator = "GT"
	ComparisonOperator_IN           ComparisonOperator = "IN"
	ComparisonOperator_LE           ComparisonOperator = "LE"
	ComparisonOperator_LT           ComparisonOperator = "LT"
	ComparisonOperator_NE           ComparisonOperator = "NE"
	ComparisonOperator_NOT_CONTAINS ComparisonOperator = "NOT_CONTAINS"
	ComparisonOperator_NOT_NULL     ComparisonOperator = "NOT_NULL"
	ComparisonOperator_NULL         ComparisonOperator = "NULL"
)

type ConditionalOperator string

const (
	ConditionalOperator_AND ConditionalOperator = "AND"
	ConditionalOperator_OR  ConditionalOperator = "OR"
)

type ContinuousBackupsStatus string

const (
	ContinuousBackupsStatus_DISABLED ContinuousBackupsStatus = "DISABLED"
	ContinuousBackupsStatus_ENABLED  ContinuousBackupsStatus = "ENABLED"
)

type ContributorInsightsAction string

const (
	ContributorInsightsAction_DISABLE ContributorInsightsAction = "DISABLE"
	ContributorInsightsAction_ENABLE  ContributorInsightsAction = "ENABLE"
)

type ContributorInsightsStatus string

const (
	ContributorInsightsStatus_DISABLED  ContributorInsightsStatus = "DISABLED"
	ContributorInsightsStatus_DISABLING ContributorInsightsStatus = "DISABLING"
	ContributorInsightsStatus_ENABLED   ContributorInsightsStatus = "ENABLED"
	ContributorInsightsStatus_ENABLING  ContributorInsightsStatus = "ENABLING"
	ContributorInsightsStatus_FAILED    ContributorInsightsStatus = "FAILED"
)

type DestinationStatus string

const (
	DestinationStatus_ACTIVE        DestinationStatus = "ACTIVE"
	DestinationStatus_DISABLED      DestinationStatus = "DISABLED"
	DestinationStatus_DISABLING     DestinationStatus = "DISABLING"
	DestinationStatus_ENABLE_FAILED DestinationStatus = "ENABLE_FAILED"
	DestinationStatus_ENABLING      DestinationStatus = "ENABLING"
	DestinationStatus_UPDATING      DestinationStatus = "UPDATING"
)

type ExportFormat string

const (
	ExportFormat_DYNAMODB_JSON ExportFormat = "DYNAMODB_JSON"
	ExportFormat_ION           ExportFormat = "ION"
)

type ExportStatus string

const (
	ExportStatus_COMPLETED   ExportStatus = "COMPLETED"
	ExportStatus_FAILED      ExportStatus = "FAILED"
	ExportStatus_IN_PROGRESS ExportStatus = "IN_PROGRESS"
)

type ExportType string

const (
	ExportType_FULL_EXPORT        ExportType = "FULL_EXPORT"
	ExportType_INCREMENTAL_EXPORT ExportType = "INCREMENTAL_EXPORT"
)

type ExportViewType string

const (
	ExportViewType_NEW_AND_OLD_IMAGES ExportViewType = "NEW_AND_OLD_IMAGES"
	ExportViewType_NEW_IMAGE          ExportViewType = "NEW_IMAGE"
)

type GlobalTableStatus_SDK string

const (
	GlobalTableStatus_SDK_ACTIVE   GlobalTableStatus_SDK = "ACTIVE"
	GlobalTableStatus_SDK_CREATING GlobalTableStatus_SDK = "CREATING"
	GlobalTableStatus_SDK_DELETING GlobalTableStatus_SDK = "DELETING"
	GlobalTableStatus_SDK_UPDATING GlobalTableStatus_SDK = "UPDATING"
)

type ImportStatus string

const (
	ImportStatus_CANCELLED   ImportStatus = "CANCELLED"
	ImportStatus_CANCELLING  ImportStatus = "CANCELLING"
	ImportStatus_COMPLETED   ImportStatus = "COMPLETED"
	ImportStatus_FAILED      ImportStatus = "FAILED"
	ImportStatus_IN_PROGRESS ImportStatus = "IN_PROGRESS"
)

type IndexStatus string

const (
	IndexStatus_ACTIVE   IndexStatus = "ACTIVE"
	IndexStatus_CREATING IndexStatus = "CREATING"
	IndexStatus_DELETING IndexStatus = "DELETING"
	IndexStatus_UPDATING IndexStatus = "UPDATING"
)

type InputCompressionType string

const (
	InputCompressionType_GZIP InputCompressionType = "GZIP"
	InputCompressionType_NONE InputCompressionType = "NONE"
	InputCompressionType_ZSTD InputCompressionType = "ZSTD"
)

type InputFormat string

const (
	InputFormat_CSV           InputFormat = "CSV"
	InputFormat_DYNAMODB_JSON InputFormat = "DYNAMODB_JSON"
	InputFormat_ION           InputFormat = "ION"
)

type KeyType string

const (
	KeyType_HASH  KeyType = "HASH"
	KeyType_RANGE KeyType = "RANGE"
)

type PointInTimeRecoveryStatus string

const (
	PointInTimeRecoveryStatus_DISABLED PointInTimeRecoveryStatus = "DISABLED"
	PointInTimeRecoveryStatus_ENABLED  PointInTimeRecoveryStatus = "ENABLED"
)

type ProjectionType string

const (
	ProjectionType_ALL       ProjectionType = "ALL"
	ProjectionType_INCLUDE   ProjectionType = "INCLUDE"
	ProjectionType_KEYS_ONLY ProjectionType = "KEYS_ONLY"
)

type ReplicaStatus string

const (
	ReplicaStatus_ACTIVE                              ReplicaStatus = "ACTIVE"
	ReplicaStatus_CREATING                            ReplicaStatus = "CREATING"
	ReplicaStatus_CREATION_FAILED                     ReplicaStatus = "CREATION_FAILED"
	ReplicaStatus_DELETING                            ReplicaStatus = "DELETING"
	ReplicaStatus_INACCESSIBLE_ENCRYPTION_CREDENTIALS ReplicaStatus = "INACCESSIBLE_ENCRYPTION_CREDENTIALS"
	ReplicaStatus_REGION_DISABLED                     ReplicaStatus = "REGION_DISABLED"
	ReplicaStatus_UPDATING                            ReplicaStatus = "UPDATING"
)

type ReturnConsumedCapacity string

const (
	ReturnConsumedCapacity_INDEXES ReturnConsumedCapacity = "INDEXES"
	ReturnConsumedCapacity_NONE    ReturnConsumedCapacity = "NONE"
	ReturnConsumedCapacity_TOTAL   ReturnConsumedCapacity = "TOTAL"
)

type ReturnItemCollectionMetrics string

const (
	ReturnItemCollectionMetrics_NONE ReturnItemCollectionMetrics = "NONE"
	ReturnItemCollectionMetrics_SIZE ReturnItemCollectionMetrics = "SIZE"
)

type ReturnValue string

const (
	ReturnValue_ALL_NEW     ReturnValue = "ALL_NEW"
	ReturnValue_ALL_OLD     ReturnValue = "ALL_OLD"
	ReturnValue_NONE        ReturnValue = "NONE"
	ReturnValue_UPDATED_NEW ReturnValue = "UPDATED_NEW"
	ReturnValue_UPDATED_OLD ReturnValue = "UPDATED_OLD"
)

type ReturnValuesOnConditionCheckFailure string

const (
	ReturnValuesOnConditionCheckFailure_ALL_OLD ReturnValuesOnConditionCheckFailure = "ALL_OLD"
	ReturnValuesOnConditionCheckFailure_NONE    ReturnValuesOnConditionCheckFailure = "NONE"
)

type S3SSEAlgorithm string

const (
	S3SSEAlgorithm_AES256 S3SSEAlgorithm = "AES256"
	S3SSEAlgorithm_KMS    S3SSEAlgorithm = "KMS"
)

type SSEStatus string

const (
	SSEStatus_DISABLED  SSEStatus = "DISABLED"
	SSEStatus_DISABLING SSEStatus = "DISABLING"
	SSEStatus_ENABLED   SSEStatus = "ENABLED"
	SSEStatus_ENABLING  SSEStatus = "ENABLING"
	SSEStatus_UPDATING  SSEStatus = "UPDATING"
)

type SSEType string

const (
	SSEType_AES256 SSEType = "AES256"
	SSEType_KMS    SSEType = "KMS"
)

type ScalarAttributeType string

const (
	ScalarAttributeType_B ScalarAttributeType = "B"
	ScalarAttributeType_N ScalarAttributeType = "N"
	ScalarAttributeType_S ScalarAttributeType = "S"
)

type Select string

const (
	Select_ALL_ATTRIBUTES           Select = "ALL_ATTRIBUTES"
	Select_ALL_PROJECTED_ATTRIBUTES Select = "ALL_PROJECTED_ATTRIBUTES"
	Select_COUNT                    Select = "COUNT"
	Select_SPECIFIC_ATTRIBUTES      Select = "SPECIFIC_ATTRIBUTES"
)

type StreamViewType string

const (
	StreamViewType_KEYS_ONLY          StreamViewType = "KEYS_ONLY"
	StreamViewType_NEW_AND_OLD_IMAGES StreamViewType = "NEW_AND_OLD_IMAGES"
	StreamViewType_NEW_IMAGE          StreamViewType = "NEW_IMAGE"
	StreamViewType_OLD_IMAGE          StreamViewType = "OLD_IMAGE"
)

type TableClass string

const (
	TableClass_STANDARD                   TableClass = "STANDARD"
	TableClass_STANDARD_INFREQUENT_ACCESS TableClass = "STANDARD_INFREQUENT_ACCESS"
)

type TableStatus_SDK string

const (
	TableStatus_SDK_ACTIVE                              TableStatus_SDK = "ACTIVE"
	TableStatus_SDK_ARCHIVED                            TableStatus_SDK = "ARCHIVED"
	TableStatus_SDK_ARCHIVING                           TableStatus_SDK = "ARCHIVING"
	TableStatus_SDK_CREATING                            TableStatus_SDK = "CREATING"
	TableStatus_SDK_DELETING                            TableStatus_SDK = "DELETING"
	TableStatus_SDK_INACCESSIBLE_ENCRYPTION_CREDENTIALS TableStatus_SDK = "INACCESSIBLE_ENCRYPTION_CREDENTIALS"
	TableStatus_SDK_UPDATING                            TableStatus_SDK = "UPDATING"
)

type TimeToLiveStatus string

const (
	TimeToLiveStatus_DISABLED  TimeToLiveStatus = "DISABLED"
	TimeToLiveStatus_DISABLING TimeToLiveStatus = "DISABLING"
	TimeToLiveStatus_ENABLED   TimeToLiveStatus = "ENABLED"
	TimeToLiveStatus_ENABLING  TimeToLiveStatus = "ENABLING"
)
